# Usar a imagem node:21.11.1-alpine como base (Atualmente a LTS)
FROM node:20.11.1-alpine

# Mudar para o diretório de trabalho /app-frontend
WORKDIR /app-frontend

# Copiar os package.json e package-lock.json para o container
COPY --chown=root:root package*.json ./

# Instalar as dependências Node
RUN npm install
# Copiar o restante dos arquivos da aplicação para o container
COPY --chown=root:root . .

# Sinalize que aplicação expõe a porta 3000
EXPOSE 3000

# Configura os comandos para iniciar a aplicação
ENTRYPOINT ["npm", "run"]
CMD [ "dev" ]
