import AppBar from '@/components/AppBar';
import QueryContext from '@/context/UseQuery';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <QueryContext>
        <body className={inter.className}>
          <AppBar />
          <main className='bg-slate-800 flex justify-center items-center min-h-screen'>
            <div className='dark:bg-slate-900/70 rounded-lg p-10 ring-1 ring-slate-900/5 shadow-xl flex justify-center items-center'>
              {children}
            </div>
          </main>
        </body>
      </QueryContext>
    </html>
  );
}
