# Usar a imagem node:21.11.1-alpine como base (Atualmente a LTS)
FROM node:20.11.1-alpine

# Mudar para o diretório de trabalho /app-backend
WORKDIR /app-backend

# Copiar os package.json, package-lock.json e packages.npm para o container
COPY package*.json ./

# Instalar as dependências Node
RUN npm install

# Copiar o restante dos arquivos da aplicação para o container
COPY . .

# Sinalize que aplicação expõe a porta 3001
EXPOSE 3001

# Configura os comandos para iniciar a aplicação
ENTRYPOINT ["npm", "run"]
CMD [ "start" ]